version: "3.8"

services:
  auth_service:
    build:
      context: .
      dockerfile: dockerfiles/auth.dockerfile
    image: hotaroudazai/auth-license-plate
    volumes:
      - ./backend/auth:/auth
    env_file:
      - ./env/auth.env
    ports:
      - "8001:8000"
  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    image: hotaroudazai/nginx-license-plate
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:80"
    depends_on:
      - auth_service
