version: '3.8'

services:
  auth_service:
    build: 
      context: .
      dockerfile: dockerfiles/auth.dockerfile
    image: hotaroudazai/auth-license-plate
    volumes:
      - ./backend/auth:/auth
    env_file:
      - ./env/auth.env
    ports:
      - '8001:8000'
  ai_service:
    build: 
      context: .
      dockerfile: dockerfiles/yolo-license-plate.dockerfile
    image: hotaroudazai/yolo-license-plate
    volumes:
      - ./backend/yolo-license-plate:/yolo-license-plate
    ports:
      - '8002:8000'
  app_service:
    build:
      context: .
      dockerfile: dockerfiles/license-plate-app.dockerfile
    image: hotaroudazai/license-plate-app
    volumes:
      - ./backend/license-plate-app:/license-plate-app
    env_file:
      - ./env/license-plate-app.env
    ports:
      - '8003:8000'
    depends_on:
      - auth_service
      - ai_service
  check_vehicle_service:
    build:
      context: .
      dockerfile: dockerfiles/check-vehicle-real-time.dockerfile
    image: hotaroudazai/check-vehicle-real-time
    volumes:
      - ./backend/check-vehicle-real-time:/check-vehicle-real-time
    ports:
      - '8004:8000'
  # redis:
  #   image: redis:alpine3.16
  #   ports:
  #     - '6379:6379'
  frontend:
    build:
      context: .
      dockerfile: dockerfiles/frontend.dockerfile
    volumes:
      - react_build:/react/build
  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    image: hotaroudazai/nginx-license-plate
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    ports:
      - '80:80'
      - '443:80'
    depends_on:
      - auth_service
      - app_service
      - ai_service
      - frontend
      # - check_vehicle_service
  # worker:
  #   image: hotaroudazai/license-plate-app
  #   command: celery -A api.tasks.worker worker --loglevel=INFO
  #   env_file:
  #     - ./env/license-plate-app.env
  #   volumes:
  #     - ./backend/license-plate-app:/license-plate-app
  #   depends_on:
  #     - app_service
volumes:
  react_build: