version: '3.8'

services:
  auth_service:
    build: 
      context: .
      dockerfile: dockerfiles/auth.dockerfile
    image: hotaroudazai/auth-license-plate
    volumes:
      - ./backend/auth:/auth
    env_file:
      - ./env/auth.env
    ports:
      - '8001:8000'
  ai_service:
    build: 
      context: .
      dockerfile: dockerfiles/yolo-license-plate.dockerfile
    image: hotaroudazai/yolo-license-plate
    volumes:
      - ./backend/yolo-license-plate:/yolo-license-plate
    ports:
      - '8002:8000'
  app_service:
    build:
      context: .
      dockerfile: dockerfiles/license-plate-app.dockerfile
    image: hotaroudazai/license-plate-app
    volumes:
      - ./backend/license-plate-app:/license-plate-app
    env_file:
      - ./env/license-plate-app.env
    ports:
      - '8003:8000'
    depends_on:
      - auth_service
      - ai_service
  # frontend_admin:
  #   build:
  #     context: .
  #     dockerfile: dockerfiles/frontend-admin.dockerfile
  #   volumes:
  #     - react_build_admin:/react/build
  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    image: hotaroudazai/nginx-license-plate
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # - react_build_admin:/var/www/react_admin
    ports:
      - '80:80'
      - '443:80'
    depends_on:
      - auth_service
      - app_service
      - ai_service
      # - frontend_admin
# volumes:
#   react_build_admin: